services:
  - type: web
    name: hybrid-ml-dashboard
    env: docker
    region: singapore
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    dockerContext: .
    dockerfilePath: Dockerfile
